# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://h:p6c6a276b507708ae146414f16790a84e4f5b4e8785f9badb48b3a1a10538e5c9@ec2-34-206-214-110.compute-1.amazonaws.com:16509

development:
  adapter: redis
  url: redis://localhost:6379/1
test:
  adapter: async
