development:
  adapter: postgresql
  encoding: unicode
  database: dave
  host: localhost
  pool: 5
  username: dave
  password: welcome

test:
  adapter: postgresql
  encoding: unicode
  database: dave
  host: localhost
  pool: 5
  username: dave
  password: welcome

production:
      adapter: postgresql
      database: postgres://sbondytaugjdqe:fe0ff547789b97
      pool: 5
      timeout: 5000
