development:
  adapter: postgresql
  encoding: unicode
  database: dave
  host: localhost
  pool: 5
  username: dave
  password: welcome

test:
  adapter: postgresql
  encoding: unicode
  database: dave
  host: localhost
  pool: 5
  username: dave
  password: welcome

production:
      adapter: postgresql
      database: postgresql-dimensional-71239
      pool: 5
      timeout: 5000
