development:
  adapter: postgresql
  encoding: unicode
  database: dave
  host: localhost
  pool: 5
  username: dave
  password: welcome

test:
  adapter: postgresql
  encoding: unicode
  database: dave
  host: localhost
  pool: 5
  username: dave
  password: welcome
